language: node_js
node_js:
  - "stable"
  
script:
  - npm run lint
  - npm test

deploy:
  provider: heroku
  api_key:
    secure: "53670070-3e0c-4b1c-b65b-7050f38e4c07"
  strategy: git    
  app:
    master: deep-00
  run:
    - restart
    - "npm start"